version: "3.8"

services: 

    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn --bind 0.0.0.0:1337 manage:app
        expose: 
            - 1337
        env_file: 
        - ./.env.prod
        restart: unless-stopped

    nginx:
        build: ./services/nginx
        ports: 
            - 80:80
            - 443:443
        depends_on: 
            - web
        restart: unless-stopped
